# -*- coding: utf-8 -*-
"""Restaurant management

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWvDK_5Mubicc6gmQxIdfTX95UztsoeL
"""

class MenuItem:
    def __init__(self, name, price, category):
        self.name = name
        self.price = price
        self.category = category

    def __str__(self):
        return f"{self.name} ({self.category}): {self.price}"


class Order:
    def __init__(self, customer):
        self.customer = customer
        self.items = []
        self.total = 0.0

    def add_item(self, item):
        self.items.append(item)
        self.total += item.price

    def generate_bill(self):
        bill = f"Bill for {self.customer.name}:\n"
        for item in self.items:
            bill += f"- {item}\n"
        bill += f"Total: {self.total}"
        return bill


class Customer:
    def __init__(self, name, phone_number):
        self.name = name
        self.phone_number = phone_number

    def __str__(self):
        return f"{self.name} ({self.phone_number})"


class Employee:
    def __init__(self, name, position):
        self.name = name
        self.position = position



menu = [
    MenuItem("lime chicken sandwhich", 10.00, "Main Course"),
    MenuItem("loaded siracha fries", 4.00, "appetizer"),
    MenuItem("lemonade", 2.00, "refreshments"),
    MenuItem("chicken wings", 8.00, "appetizer"),
    MenuItem("cheeseburger", 7.00, "Main Course"),
    MenuItem("strawberry cheesecake", 8.00, "dessert"),
    MenuItem("caramel frappuccino",7.00, "refreshment")
]


customer1 = Customer("Alice", "555-1234")
order1 = Order(customer1)
order1.add_item(menu[0])
order1.add_item(menu[1])
order1.add_item(menu[2])
order1.add_item(menu[3])
order1.add_item(menu[4])
order1.add_item(menu[5])
order1.add_item(menu[6])


print(order1.generate_bill())

